import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get one command-line argument: an int value
 * 	that determines how many families to simulate.
 */

		//// Put your code here
		
/**
 *  Simulates the formation of a family in which the parents decide 
 *  to have children until they have at least one child of each gender.
 */
		int num = Integer.parseInt(args[0]);
		String answer = "";
		boolean g = false;
		boolean b = false;
		int pick;
		int countt= 0;
		int avgkids= 0;
		int twokids = 0;
		int threekids= 0;
		int fourmore= 0;
		for (int i=0; i<num; i++){
			g=false;
			b=false;
			countt=0;

			do {
				pick = (int) (Math.random()*2);
				if (pick == 1) {
					g = true;
					
					//answer += "g ";
					}else {
					b = true;	
				}
				countt++;
			}
				while (!b||!g);
			
				
				avgkids+=countt;
				if (countt==2){
					twokids++;
				}else if (countt==3){
					threekids++;
				}else if (countt>=4){
					fourmore++;
				
				}
			}
					
					System.out.println("Average: " + ((double) avgkids)/((double)num));
					System.out.println("Number of families with 2 children: " + twokids);
					System.out.println("Number of families with 3 children: " + threekids);
					System.out.println("Number of families with 4 or more children: " + fourmore);

				

						}
			



	}


		    
	

